language: python
dist: trusty
python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"
install:
   - pip install -r requirements.txt -r requirements-dev.txt
script:
   - py.test --cache-clear --flake8 mdx_attr_cols.py tests.py
